


var type_matchup_list = [
	#[Attck Type, Defend Type, Damage Mult]
	#Normal Attack
	["NORMAL", "ROCK", 0.5],
	["NORMAL", "STEEL", 0.5],
	["NORMAL", "GHOST", 0.0],
	#Fire Attack
	["FIRE", "ICE", 2.0],
	["FIRE", "BUG", 2.0],
	["FIRE", "FIRE", 0.5],
	["FIRE", "WATER", 0.5],
	["FIRE", "GRASS", 0.5],
	["FIRE", "ROCK", 0.5],
	["FIRE", "DRAGON", 0.5],
	["FIRE", "STEEL", 0.5],
	#Water Attack
	["WATER", "FIRE", 2.0],
	["WATER", "GROUND", 2.0],
	["WATER", "ROCK", 2.0],
	["WATER", "WATER", 0.5],
	["WATER", "GRASS", 0.5],
	["WATER", "DRAGON", 0.5],
	#Grass Attack
	["GRASS", "WATER", 2.0],
	["GRASS", "GROUND", 2.0],
	["GRASS", "ROCK", 2.0],
	["GRASS", "FIRE", 0.5],
	["GRASS", "GRASS", 0.5],
	["GRASS", "POISON", 0.5],
	["GRASS", "FLYING", 0.5],
	["GRASS", "BUG", 0.5],
	["GRASS", "DRAGON", 0.5],
	["GRASS", "STEEL", 0.5],
	#Electric Attack
	["ELECTRIC", "WATER", 2.0],
	["ELECTRIC", "FLYING", 2.0],
	["ELECTRIC", "GRASS", 0.5],
	["ELECTRIC", "ELECTRIC", 0.5],
	["ELECTRIC", "DRAGON", 0.5],
	["ELECTRIC", "GROUND", 0.0],
	#Ice Attack
	["ICE", "GRASS", 2.0],
	["ICE", "GROUND", 2.0],
	["ICE", "FLYING", 2.0],
	["ICE", "DRAGON", 2.0],
	["ICE", "FIRE", 0.5],
	["ICE", "WATER", 0.5],
	["ICE", "ICE", 0.5],
	["ICE", "STEEL", 0.5],
	#Fighting Attack
	["FIGHTING", "NORMAL", 2.0],
	["FIGHTING", "ICE", 2.0],
	["FIGHTING", "ROCK", 2.0],
	["FIGHTING", "DARK", 2.0],
	["FIGHTING", "STEEL", 2.0],
	["FIGHTING", "POISON", 0.5],
	["FIGHTING", "FLYING", 0.5],
	["FIGHTING", "PSYCHIC", 0.5],
	["FIGHTING", "BUG", 0.5],
	["FIGHTING", "FAIRY", 0.5],
	["FIGHTING", "GHOST", 0.0],
	#Poison Attack
	["POISON", "GRASS", 2.0],
	["POISON", "FAIRY", 2.0],
	["POISON", "POISON", 0.5],
	["POISON", "GROUND", 0.5],
	["POISON", "ROCK", 0.5],
	["POISON", "GHOST", 0.5],
	["POISON", "STEEL", 0.0],
	#Ground Attack
	["GROUND", "FIRE", 2.0],
	["GROUND", "ELECTRIC", 2.0],
	["GROUND", "POISON", 2.0],
	["GROUND", "ROCK", 2.0],
	["GROUND", "STEEL", 2.0],
	["GROUND", "GRASS", 0.5],
	["GROUND", "BUG", 0.5],
	["GROUND", "FLYING", 0.0],
	#Flying Attack
	["FLYING", "GRASS", 2.0],
	["FLYING", "FIGHTING", 2.0],
	["FLYING", "BUG", 2.0],
	["FLYING", "ELECTRIC", 0.5],
	["FLYING", "ROCK", 0.5],
	["FLYING", "STEEL", 0.5],
	#Psychic Attack
	["PSYCHIC", "FIGHTING", 2.0],
	["PSYCHIC", "POISON", 2.0],
	["PSYCHIC", "PSYCHIC", 0.5],
	["PSYCHIC", "STEEL", 0.5],
	["PSYCHIC", "DARK", 0.0],
	#Bug Attack
	["BUG", "GRASS", 2.0],
	["BUG", "PSYCHIC", 2.0],
	["BUG", "DARK", 2.0],
	["BUG", "FIRE", 0.5],
	["BUG", "FIGHTING", 0.5],
	["BUG", "POISON", 0.5],
	["BUG", "FLYING", 0.5],
	["BUG", "GHOST", 0.5],
	["BUG", "STEEL", 0.5],
	["BUG", "FAIRY", 0.5],
	#Rock Attack
	["ROCK", "FIRE", 2.0],
	["ROCK", "ICE", 2.0],
	["ROCK", "FLYING", 2.0],
	["ROCK", "BUG", 2.0],
	["ROCK", "FIGHTING", 0.5],
	["ROCK", "GROUND", 0.5],
	["ROCK", "STEEL", 0.5],
	#Ghost Attack
	["GHOST", "PSYCHIC", 2.0],
	["GHOST", "GHOST", 2.0],
	["GHOST", "DARK", 0.5],
	["GHOST", "NORMAL", 0.0],
	#Dragon Attack
	["DRAGON", "DRAGON", 2.0],
	["DRAGON", "STEEL", 0.5],
	["DRAGON", "FAIRY", 0.0],
	#Dark Attack
	["DARK", "PSYCHIC", 2.0],
	["DARK", "GHOST", 2.0],
	["DARK", "FIGHTING", 0.5],
	["DARK", "DARK", 0.5],
	["DARK", "FAIRY", 0.5],
	#Steel Attack
	["STEEL", "ICE", 2.0],
	["STEEL", "ROCK", 2.0],
	["STEEL", "FAIRY", 2.0],
	["STEEL", "FIRE", 0.5],
	["STEEL", "WATER", 0.5],
	["STEEL", "ELECTRIC", 0.5],
	["STEEL", "STEEL", 0.5],
	#Fairy Attack
	["FAIRY", "FIGHTING", 2.0],
	["FAIRY", "DRAGON", 2.0],
	["FAIRY", "DARK", 2.0],
	["FAIRY", "FIRE", 0.5],
	["FAIRY", "POISON", 0.5],
	["FAIRY", "STEEL", 0.5],
]
